spring.data.redis.host=localhost
spring.data.redis.port=6379

#local
#spring.datasource.url=jdbc:postgresql://localhost:5432/ECommerce

#test
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_jmeter
spring.datasource.username=postgres
spring.datasource.password=123

#RabbitMq locally working
spring.rabbitmq.host=localhost