spring.application.name=e-comerce
spring.datasource.url=jdbc:postgresql://localhost:5432/ECommerce
spring.datasource.username=postgres
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
jwt.secret=K7f3n9XyZp2Qw8Rt5Vb1Mn6Jh4Gd0Sl3Ck9Ea7Uy2Wo=