spring.application.name=e-comerce
spring.datasource.url=jdbc:postgresql://localhost:5432/ECommerce
spring.datasource.username=postgres
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
jwt.secret=K7f3n9XyZp2Qw8Rt5Vb1Mn6Jh4Gd0Sl3Ck9Ea7Uy2Wo=
aws.s3.bucket=aws-s3-ecom-bucket
aws.region=eu-north-1
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true