spring.data.redis.url=rediss://default:${UPSTASH_REDIS_TOKEN}@classic-dove-149593.upstash.io:6379

spring.datasource.url=jdbc:postgresql://meezan-db.c3wow0qkwxlb.ap-south-1.rds.amazonaws.com:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

#RabbitMq host bcz of docker network
spring.rabbitmq.host=rabbitmq