spring.application.name=e-comerce
spring.datasource.url=jdbc:postgresql://localhost:5432/ECommerce
spring.datasource.username=postgres
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update