spring.data.redis.url=rediss://default:${UPSTASH_REDIS_TOKEN}@classic-dove-149593.upstash.io:6379

spring.datasource.url=jdbc:postgresql://database-1.cid26oka8abu.us-east-1.rds.amazonaws.com:5432/ECOMERCE
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}